version: "3"

services:
  friend-board-db:
    image: mysql:5.7
    # DB文字コードをutf8に設定
    command: mysqld --character-set-server=utf8mb4
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: development_db
    volumes:
      # 設定ファイル外だし
      - './mysql/etc/my.cnf:/etc/my.cnf'
  friend-board-web:
    # 自作カスタムイメージ使用
    image: gawach/friend-board
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - ./web_app:/usr/src/app
    ports:
      - 3000:3000
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: development_db
    depends_on:
      - friend-board-db
    tty: true
    stdin_open: true
